version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  mongodb:
    image: mongo
    command: mongod --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
